# seed-docker.ps1 - populate an EXTERNAL Clara Network target database (e.g.
# Supabase/Postgres) with demo data by running the compose data sims against it.
# PowerShell 5.1 compatible. Windows-first; seed.sh is the Linux/macOS twin.
#
# Usage:
#   $env:CLARA_PG_DSN="postgres://user:pass@host:5432/db?sslmode=require"
#   .\seed-docker.ps1
# (CLARA_PG_DSN falls back to DATABASE_URL.)

$ErrorActionPreference = "Stop"

$scriptDir = $PSScriptRoot
if (-not $scriptDir) {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
}
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $scriptDir "..\.."))
$composeFile = Join-Path $repoRoot "deploy\docker-compose.yml"

if (-not (Test-Path -LiteralPath $composeFile)) {
    Write-Host "[seed] ERROR: compose file not found: $composeFile" -ForegroundColor Red
    exit 1
}
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "[seed] ERROR: docker not found on PATH" -ForegroundColor Red
    exit 1
}

$dsn = $env:CLARA_PG_DSN
if (-not $dsn) {
    $dsn = $env:DATABASE_URL
}
if (-not $dsn) {
    Write-Host @"
[seed] ERROR: no target database DSN provided.
Set CLARA_PG_DSN (or DATABASE_URL) before running, e.g.:
  `$env:CLARA_PG_DSN="postgres://user:pass@host:5432/db?sslmode=require"
  .\seed-docker.ps1
"@ -ForegroundColor Red
    exit 1
}

$dsnYaml = "'" + ($dsn.Replace("'", "''")) + "'"
$overridePath = Join-Path ([System.IO.Path]::GetTempPath()) ("clara-seed-override-" + $PID + ".yml")

$overrideContent = @"
# Temporary override generated by seed-docker.ps1 - points the data services at
# the external target DB. Deleted on exit. Do not edit.
services:
  postgres:
    ports: !reset []
"@
foreach ($svc in @("switch", "cardsvc", "clearing-sim", "ledger-sim", "card-sim", "acquiring-sim", "disputes-sim")) {
    $overrideContent += @"

  ${svc}:
    environment:
      CLARA_PG_DSN: $dsnYaml
"@
}

function Invoke-Compose {
    param(
        [string[]]$Arguments,
        [string]$Label
    )
    Write-Host "[seed] $Label"
    & docker @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "[seed] docker compose failed ($Label): exit code $LASTEXITCODE"
    }
}

$startedBackground = $false
try {
    [System.IO.File]::WriteAllText($overridePath, $overrideContent, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "[seed] wrote compose override: $overridePath"

    $baseArgs = @("compose", "-f", $composeFile, "-f", $overridePath)

    Invoke-Compose -Arguments ($baseArgs + @("up", "-d", "--build", "redis", "switch", "cardsvc")) -Label "starting redis, switch, cardsvc (image builds on first run)"
    $startedBackground = $true

    Write-Host "[seed] waiting for cardsvc to accept connections (localhost:18081, up to 60s)..."
    $ready = $false
    $deadline = (Get-Date).AddSeconds(60)
    while ((Get-Date) -lt $deadline) {
        $tcp = New-Object System.Net.Sockets.TcpClient
        try {
            $tcp.Connect("localhost", 18081)
            $ready = $true
        } catch {
            Start-Sleep -Seconds 2
        } finally {
            $tcp.Dispose()
        }
        if ($ready) {
            break
        }
    }
    if (-not $ready) {
        Write-Host "[seed] ERROR: cardsvc did not become ready on localhost:18081 within 60s" -ForegroundColor Red
        & docker @($baseArgs + @("logs", "--tail", "100", "cardsvc"))
        throw "cardsvc readiness timeout"
    }
    Write-Host "[seed] cardsvc is ready"

    foreach ($svc in @("clearing-sim", "ledger-sim", "card-sim", "acquiring-sim", "disputes-sim")) {
        Invoke-Compose -Arguments ($baseArgs + @("run", "--rm", "--no-deps", $svc)) -Label "running one-shot $svc (clearing/ledger/cards/merchants/disputes)"
    }

    Invoke-Compose -Arguments ($baseArgs + @("run", "--rm", "--no-deps", "acquirer-sim")) -Label "running acquirer-sim to generate authorizations through the running switch"
} catch {
    Write-Host "[seed] ERROR: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
} finally {
    if ($startedBackground) {
        try {
            & docker @(@("compose", "-f", $composeFile, "-f", $overridePath) + @("stop", "postgres", "redis", "switch", "cardsvc")) | Out-Null
            Write-Host "[seed] stopped background services (postgres, redis, switch, cardsvc)"
        } catch {
            Write-Host "[seed] WARN: background teardown failed: $($_.Exception.Message)"
        }
    }
    if (Test-Path -LiteralPath $overridePath) {
        Remove-Item -LiteralPath $overridePath -Force
    }
}

$credentialRegex = '^[a-zA-Z][a-zA-Z0-9+.\-]*://[^@/]*@'
if ($dsn -match $credentialRegex) {
    $masked = $dsn -replace $credentialRegex, '' -replace '\?.*$', ''
} else {
    $masked = $dsn -replace '\?.*$', ''
}
Write-Host "seed complete (target: $masked)"